server:
     port: 8081

spring:
     application:
          name: apis-cognitivas-maria-sulca
     data:
          mongodb:
               uri: mongodb+srv://mariasulcab_db_user:eXmgDOKzpecB9Q2n@apis.cvvnnd0.mongodb.net/?retryWrites=true&w=majority&appName=apis
               database: cognitive-apis

translate:
     api:
          url: https://deep-translate1.p.rapidapi.com/language/translate/v2
          key: a7e8d45870msh89cd6a7d8bce39ep1c94b7jsn20bbed3d61b7
          host: deep-translate1.p.rapidapi.com

youtube:
     api:
          url: https://youtube-media-downloader.p.rapidapi.com/v2/video/details
          key: a7e8d45870msh89cd6a7d8bce39ep1c94b7jsn20bbed3d61b7
          host: youtube-media-downloader.p.rapidapi.com

springdoc:
     api-docs:
          path: /v3/api-docs
          enabled: true
     swagger-ui:
          path: /swagger-ui/index.html
          enabled: true
          try-it-out-enabled: true
          display-request-duration: true
     packages-to-scan: pe.edu.vallegrande.apicognitivas
     show-actuator: false
